spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.133.131:8761/eureka/,http://192.168.133.131:8861/eureka/,http://192.168.133.131:8961/eureka/
